### ISSUE TITLE
Human-paraphrased easy/hard split?

### ISSUE THREAD

**Issue by NoviScl** [wenhuchen/Time-Sensitive-QA#4]
It seems that for the human-paraphrased sets, the easy and hard splits contain the same data. Is this just how it's constructed or is there a mistake in the data release?

**Comment by wenhuchen** [comment]
Hi, I looked into these files under dataset/, they are not the same. Is there any chance that you downloaded the wrong version?

If you want to replicate the easy/hard qgen process, you can open https://github.com/wenhuchen/Time-Sensitive-QA/blob/main/Process.ipynb and scroll down to "Generating easy/hard Human rewritten questions". I think the notebook will help you understand how it's generated.

**Comment by NoviScl** [comment]
Thanks for the quick response Wenhu! I double-checked and yeah you are right they are not the same, altho there seems to be an overlap of about ~100 questions between the hard & easy splits (based on the data generation script I guess those are cases whether the time is not a tuple but rather just a single time stamp like 'in year xxx' ?). But anyway this should be fine, thanks for clarifying!
