### ISSUE TITLE
Trained Models

### ISSUE THREAD

**Issue by xinsu626** [wenhuchen/Time-Sensitive-QA#5]
Hello, sorry, I have one more question. I was wondering if it's possible that you could release trained checkpoints, especially FiD models trained on the easy version of the dataset.

**Comment by wenhuchen** [comment]
It's been a while, I probably won't be able to find the checkpoint. But the original FiD checkpoint is there, which doesn't take long to finetune.

**Comment by xinsu626** [comment]
> It's been a while, I probably won't be able to find the checkpoint. But the original FiD checkpoint is there, which doesn't take long to finetune.

Hi @wenhuchen, thanks for your reply. Sorry for commenting on a closed issue. Do you mind sharing the detailed hyperparameters used for training the FiD model on the easy version of the dataset? I was able to get a similar performance on the dev.hard dataset, but the best performance on easy.dev I got used the default settings in [config.yaml](https://github.com/wenhuchen/Time-Sensitive-QA/blob/main/FiD/config.yaml) is `('exact', 54.319761668321746), ('f1', 63.80402672963455)`.
