### ISSUE TITLE
Dataset description 

### ISSUE THREAD

**Issue by satya77** [wenhuchen/Time-Sensitive-QA#9]
Could you provide a description of the difference between the data in the dataset folder? From the README file, it is not clear what is the difference between (train/test/dev), annotated _(train/test/dev) and human_annotated_(train/test/dev)? Which one have you used for evaluation in the paper?

**Comment by wenhuchen** [comment]
I think the only datasets we used are depicted in https://github.com/wenhuchen/Time-Sensitive-QA/tree/main/FiD/dataset. The others are intermediate files.
